const WORDS = [
  "Beboppin'",
  'Boondoggling',
  'Booping',
  'Canoodling',
  'Dilly-dallying',
  'Discombobulating',
  'Fiddle-faddling',
  'Finagling',
  'Flibbertigibbeting',
  'Flummoxing',
  'Frolicking',
  'Gallivanting',
  'Hullaballooing',
  'Lollygagging',
  'Moseying',
  'Noodling',
  'Osmosing',
  'Pontificating',
  'Puttering',
  'Razzle-dazzling',
  'Razzmatazzing',
  'Recombobulating',
  'Reticulating',
  'Schlepping',
  'Shenaniganing',
  'Shimmying',
  'Skedaddling',
  'Slithering',
  'Smooshing',
  'Sock-hopping',
  'Spelunking',
  'Tomfoolering',
  'Topsy-turvying',
  'Vibing',
  'Waddling',
  'Whatchamacalliting',
  'Wibbling',
  'Zigzagging',
];

export function randomLoadingWord(): string {
  return WORDS[Math.floor(Math.random() * WORDS.length)];
}
